enable_mutex_lock: false
user: puppet
pass: puppet
protected: true
client_cfg: "/var/lib/peadmin/.mcollective"
client_timeout: "120"
use_mco_ruby: false
use_mcollective: false
slack_webhook: false
generate_types: false
slack_channel: '#default'
slack_username: 'r10k'
slack_proxy_url: ~
default_branch: production
discovery_timeout: '10'
ignore_environments: []
prefix: ~
prefix_command: ''
r10k_deploy_arguments: "-pv"
allow_uppercase: true
github_secret: ~
repository_events: ~
