server_type: simple
logfile: /var/log/puppet_webhook/access.log
pidfile: /var/run/puppet_webhook/webhook.pid
lockfile: /var/run/puppet_webhook/webhook.lock
approot: './'
server_software: PuppetWebhook
bind_address: 0.0.0.0
port: 8088
enable_ssl: false
verify_ssl: false
public_key_path: ''
private_key_path: ''
command_prefix: 'umask 0022;'
